package pl.edu.agh.northwind;

// Generated 2014-05-13 06:34:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories implements java.io.Serializable {

	private BigDecimal categoryid;
	private String categoryname;
	private Blob description;
	private Blob picture;
	private Set productses = new HashSet(0);

	public Categories() {
	}

	public Categories(String categoryname) {
		this.categoryname = categoryname;
	}

	public Categories(String categoryname, Blob description, Blob picture,
			Set productses) {
		this.categoryname = categoryname;
		this.description = description;
		this.picture = picture;
		this.productses = productses;
	}

	public BigDecimal getCategoryid() {
		return this.categoryid;
	}

	public void setCategoryid(BigDecimal categoryid) {
		this.categoryid = categoryid;
	}

	public String getCategoryname() {
		return this.categoryname;
	}

	public void setCategoryname(String categoryname) {
		this.categoryname = categoryname;
	}

	public Blob getDescription() {
		return this.description;
	}

	public void setDescription(Blob description) {
		this.description = description;
	}

	public Blob getPicture() {
		return this.picture;
	}

	public void setPicture(Blob picture) {
		this.picture = picture;
	}

	public Set getProductses() {
		return this.productses;
	}

	public void setProductses(Set productses) {
		this.productses = productses;
	}

}
