package pl.edu.agh.northwind;

// Generated 2014-05-13 06:34:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employees generated by hbm2java
 */
public class Employees implements java.io.Serializable {

	private BigDecimal employeeid;
	private String lastname;
	private String firstname;
	private String title;
	private String titleofcourtesy;
	private Date birthdate;
	private Date hiredate;
	private String address;
	private String city;
	private String region;
	private String postalcode;
	private String country;
	private String homephone;
	private String extension;
	private Blob photo;
	private Blob notes;
	private BigDecimal reportsto;
	private String photopath;
	private Set orderses = new HashSet(0);

	public Employees() {
	}

	public Employees(String lastname, String firstname) {
		this.lastname = lastname;
		this.firstname = firstname;
	}

	public Employees(String lastname, String firstname, String title,
			String titleofcourtesy, Date birthdate, Date hiredate,
			String address, String city, String region, String postalcode,
			String country, String homephone, String extension, Blob photo,
			Blob notes, BigDecimal reportsto, String photopath, Set orderses) {
		this.lastname = lastname;
		this.firstname = firstname;
		this.title = title;
		this.titleofcourtesy = titleofcourtesy;
		this.birthdate = birthdate;
		this.hiredate = hiredate;
		this.address = address;
		this.city = city;
		this.region = region;
		this.postalcode = postalcode;
		this.country = country;
		this.homephone = homephone;
		this.extension = extension;
		this.photo = photo;
		this.notes = notes;
		this.reportsto = reportsto;
		this.photopath = photopath;
		this.orderses = orderses;
	}

	public BigDecimal getEmployeeid() {
		return this.employeeid;
	}

	public void setEmployeeid(BigDecimal employeeid) {
		this.employeeid = employeeid;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getTitleofcourtesy() {
		return this.titleofcourtesy;
	}

	public void setTitleofcourtesy(String titleofcourtesy) {
		this.titleofcourtesy = titleofcourtesy;
	}

	public Date getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	public Date getHiredate() {
		return this.hiredate;
	}

	public void setHiredate(Date hiredate) {
		this.hiredate = hiredate;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getPostalcode() {
		return this.postalcode;
	}

	public void setPostalcode(String postalcode) {
		this.postalcode = postalcode;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getHomephone() {
		return this.homephone;
	}

	public void setHomephone(String homephone) {
		this.homephone = homephone;
	}

	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	public Blob getPhoto() {
		return this.photo;
	}

	public void setPhoto(Blob photo) {
		this.photo = photo;
	}

	public Blob getNotes() {
		return this.notes;
	}

	public void setNotes(Blob notes) {
		this.notes = notes;
	}

	public BigDecimal getReportsto() {
		return this.reportsto;
	}

	public void setReportsto(BigDecimal reportsto) {
		this.reportsto = reportsto;
	}

	public String getPhotopath() {
		return this.photopath;
	}

	public void setPhotopath(String photopath) {
		this.photopath = photopath;
	}

	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

}
