package pl.edu.agh.northwind;

// Generated 2014-05-13 06:34:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * OrderDetailsId generated by hbm2java
 */
public class OrderDetailsId implements java.io.Serializable {

	private BigDecimal orderid;
	private BigDecimal productid;

	public OrderDetailsId() {
	}

	public OrderDetailsId(BigDecimal orderid, BigDecimal productid) {
		this.orderid = orderid;
		this.productid = productid;
	}

	public BigDecimal getOrderid() {
		return this.orderid;
	}

	public void setOrderid(BigDecimal orderid) {
		this.orderid = orderid;
	}

	public BigDecimal getProductid() {
		return this.productid;
	}

	public void setProductid(BigDecimal productid) {
		this.productid = productid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderDetailsId))
			return false;
		OrderDetailsId castOther = (OrderDetailsId) other;

		return ((this.getOrderid() == castOther.getOrderid()) || (this
				.getOrderid() != null && castOther.getOrderid() != null && this
				.getOrderid().equals(castOther.getOrderid())))
				&& ((this.getProductid() == castOther.getProductid()) || (this
						.getProductid() != null
						&& castOther.getProductid() != null && this
						.getProductid().equals(castOther.getProductid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getOrderid() == null ? 0 : this.getOrderid().hashCode());
		result = 37 * result
				+ (getProductid() == null ? 0 : this.getProductid().hashCode());
		return result;
	}

}
