package pl.edu.agh.northwind;

// Generated 2014-05-13 14:44:40 by Hibernate Tools 3.4.0.CR1

/**
 * OrderDetailsId generated by hbm2java
 */
public class OrderDetailsId implements java.io.Serializable {

	private Orders orders;
	private Products products;

	public OrderDetailsId() {
	}

	public OrderDetailsId(Orders orders, Products products) {
		this.orders = orders;
		this.products = products;
	}

	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrderDetailsId))
			return false;
		OrderDetailsId castOther = (OrderDetailsId) other;

		return ((this.getOrders() == castOther.getOrders()) || (this
				.getOrders() != null && castOther.getOrders() != null && this
				.getOrders().equals(castOther.getOrders())))
				&& ((this.getProducts() == castOther.getProducts()) || (this
						.getProducts() != null
						&& castOther.getProducts() != null && this
						.getProducts().equals(castOther.getProducts())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getOrders() == null ? 0 : this.getOrders().hashCode());
		result = 37 * result
				+ (getProducts() == null ? 0 : this.getProducts().hashCode());
		return result;
	}

}
