package pl.edu.agh.northwind;

// Generated 2014-05-13 14:44:40 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private BigDecimal orderid;
	private Employees employees;
	private Customers customers;
	private String orderdate;
	private String requireddate;
	private String shippeddate;
	private BigDecimal shipvia;
	private BigDecimal freight;
	private String shipname;
	private String shipaddress;
	private String shipcity;
	private String shipregion;
	private String shippostalcode;
	private String shipcountry;
	private Set orderDetailses = new HashSet(0);

	public Orders() {
	}

	public Orders(Employees employees, Customers customers, String orderdate,
			String requireddate, String shippeddate, BigDecimal shipvia,
			BigDecimal freight, String shipname, String shipaddress,
			String shipcity, String shipregion, String shippostalcode,
			String shipcountry, Set orderDetailses) {
		this.employees = employees;
		this.customers = customers;
		this.orderdate = orderdate;
		this.requireddate = requireddate;
		this.shippeddate = shippeddate;
		this.shipvia = shipvia;
		this.freight = freight;
		this.shipname = shipname;
		this.shipaddress = shipaddress;
		this.shipcity = shipcity;
		this.shipregion = shipregion;
		this.shippostalcode = shippostalcode;
		this.shipcountry = shipcountry;
		this.orderDetailses = orderDetailses;
	}

	public BigDecimal getOrderid() {
		return this.orderid;
	}

	public void setOrderid(BigDecimal orderid) {
		this.orderid = orderid;
	}

	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	public Customers getCustomers() {
		return this.customers;
	}

	public void setCustomers(Customers customers) {
		this.customers = customers;
	}

	public String getOrderdate() {
		return this.orderdate;
	}

	public void setOrderdate(String orderdate) {
		this.orderdate = orderdate;
	}

	public String getRequireddate() {
		return this.requireddate;
	}

	public void setRequireddate(String requireddate) {
		this.requireddate = requireddate;
	}

	public String getShippeddate() {
		return this.shippeddate;
	}

	public void setShippeddate(String shippeddate) {
		this.shippeddate = shippeddate;
	}

	public BigDecimal getShipvia() {
		return this.shipvia;
	}

	public void setShipvia(BigDecimal shipvia) {
		this.shipvia = shipvia;
	}

	public BigDecimal getFreight() {
		return this.freight;
	}

	public void setFreight(BigDecimal freight) {
		this.freight = freight;
	}

	public String getShipname() {
		return this.shipname;
	}

	public void setShipname(String shipname) {
		this.shipname = shipname;
	}

	public String getShipaddress() {
		return this.shipaddress;
	}

	public void setShipaddress(String shipaddress) {
		this.shipaddress = shipaddress;
	}

	public String getShipcity() {
		return this.shipcity;
	}

	public void setShipcity(String shipcity) {
		this.shipcity = shipcity;
	}

	public String getShipregion() {
		return this.shipregion;
	}

	public void setShipregion(String shipregion) {
		this.shipregion = shipregion;
	}

	public String getShippostalcode() {
		return this.shippostalcode;
	}

	public void setShippostalcode(String shippostalcode) {
		this.shippostalcode = shippostalcode;
	}

	public String getShipcountry() {
		return this.shipcountry;
	}

	public void setShipcountry(String shipcountry) {
		this.shipcountry = shipcountry;
	}

	public Set getOrderDetailses() {
		return this.orderDetailses;
	}

	public void setOrderDetailses(Set orderDetailses) {
		this.orderDetailses = orderDetailses;
	}

}
