package pl.edu.agh.northwind;

// Generated 2014-05-13 14:44:40 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * OrderDetails generated by hbm2java
 */
public class OrderDetails implements java.io.Serializable {

	private OrderDetailsId id;
	private BigDecimal unitprice;
	private BigDecimal quantity;
	private BigDecimal discount;

	public OrderDetails() {
	}

	public OrderDetails(OrderDetailsId id, BigDecimal unitprice,
			BigDecimal quantity, BigDecimal discount) {
		this.id = id;
		this.unitprice = unitprice;
		this.quantity = quantity;
		this.discount = discount;
	}

	public OrderDetailsId getId() {
		return this.id;
	}

	public void setId(OrderDetailsId id) {
		this.id = id;
	}

	public BigDecimal getUnitprice() {
		return this.unitprice;
	}

	public void setUnitprice(BigDecimal unitprice) {
		this.unitprice = unitprice;
	}

	public BigDecimal getQuantity() {
		return this.quantity;
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

}
