package pl.edu.agh.northwind;

// Generated 2014-05-13 06:34:59 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * OrderDetails generated by hbm2java
 */
public class OrderDetails implements java.io.Serializable {

	private OrderDetailsId id;
	private Products products;
	private Orders orders;
	private BigDecimal unitprice;
	private BigDecimal quantity;
	private BigDecimal discount;

	public OrderDetails() {
	}

	public OrderDetails(OrderDetailsId id, Products products, Orders orders,
			BigDecimal unitprice, BigDecimal quantity, BigDecimal discount) {
		this.id = id;
		this.products = products;
		this.orders = orders;
		this.unitprice = unitprice;
		this.quantity = quantity;
		this.discount = discount;
	}

	public OrderDetailsId getId() {
		return this.id;
	}

	public void setId(OrderDetailsId id) {
		this.id = id;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	public BigDecimal getUnitprice() {
		return this.unitprice;
	}

	public void setUnitprice(BigDecimal unitprice) {
		this.unitprice = unitprice;
	}

	public BigDecimal getQuantity() {
		return this.quantity;
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

}
