package pl.edu.agh.northwind;

// Generated 2014-05-13 14:44:40 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

	private BigDecimal productid;
	private Categories categories;
	private Suppliers suppliers;
	private String productname;
	private String quantityperunit;
	private BigDecimal unitprice;
	private BigDecimal unitsinstock;
	private BigDecimal unitsonorder;
	private BigDecimal reorderlevel;
	private BigDecimal discontinued;
	private Set orderDetailses = new HashSet(0);

	public Products() {
	}

	public Products(String productname, BigDecimal discontinued) {
		this.productname = productname;
		this.discontinued = discontinued;
	}

	public Products(Categories categories, Suppliers suppliers,
			String productname, String quantityperunit, BigDecimal unitprice,
			BigDecimal unitsinstock, BigDecimal unitsonorder,
			BigDecimal reorderlevel, BigDecimal discontinued, Set orderDetailses) {
		this.categories = categories;
		this.suppliers = suppliers;
		this.productname = productname;
		this.quantityperunit = quantityperunit;
		this.unitprice = unitprice;
		this.unitsinstock = unitsinstock;
		this.unitsonorder = unitsonorder;
		this.reorderlevel = reorderlevel;
		this.discontinued = discontinued;
		this.orderDetailses = orderDetailses;
	}

	public BigDecimal getProductid() {
		return this.productid;
	}

	public void setProductid(BigDecimal productid) {
		this.productid = productid;
	}

	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	public Suppliers getSuppliers() {
		return this.suppliers;
	}

	public void setSuppliers(Suppliers suppliers) {
		this.suppliers = suppliers;
	}

	public String getProductname() {
		return this.productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	public String getQuantityperunit() {
		return this.quantityperunit;
	}

	public void setQuantityperunit(String quantityperunit) {
		this.quantityperunit = quantityperunit;
	}

	public BigDecimal getUnitprice() {
		return this.unitprice;
	}

	public void setUnitprice(BigDecimal unitprice) {
		this.unitprice = unitprice;
	}

	public BigDecimal getUnitsinstock() {
		return this.unitsinstock;
	}

	public void setUnitsinstock(BigDecimal unitsinstock) {
		this.unitsinstock = unitsinstock;
	}

	public BigDecimal getUnitsonorder() {
		return this.unitsonorder;
	}

	public void setUnitsonorder(BigDecimal unitsonorder) {
		this.unitsonorder = unitsonorder;
	}

	public BigDecimal getReorderlevel() {
		return this.reorderlevel;
	}

	public void setReorderlevel(BigDecimal reorderlevel) {
		this.reorderlevel = reorderlevel;
	}

	public BigDecimal getDiscontinued() {
		return this.discontinued;
	}

	public void setDiscontinued(BigDecimal discontinued) {
		this.discontinued = discontinued;
	}

	public Set getOrderDetailses() {
		return this.orderDetailses;
	}

	public void setOrderDetailses(Set orderDetailses) {
		this.orderDetailses = orderDetailses;
	}

}
